version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_bloc3
    environment:
      MYSQL_ROOT_PASSWORD: NIEN97BF21OZEFJOZEO
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: